"""
Epistemological Quarantine Validator (§2.1, §2.2)

Enforces the strict data pipeline rules:
  - Pre-1930 sources only for classical corpus
  - Post-1930 from approved primary-source APIs only
  - No secondary sources, editorials, or encyclopedic summaries
"""

from __future__ import annotations

import hashlib
import json
import re
from datetime import datetime
from pathlib import Path
from typing import Any


# Approved modern data sources (API endpoints)
APPROVED_SOURCES = frozenset({
    "courtlistener.com",     # RECAP / Free Law Project
    "case.law",              # Harvard CAP
    "zenodo.org",            # CERN Zenodo
    "catalog.data.gov",      # Data.gov CKAN
    "nsarchive.gwu.edu",     # DNSA (deferred)
    "arxiv.org",             # STEM
    "seclists.org",          # Cyber
})

# Markers for AI-generated text to avoid "AI Inbreeding" (§2.5)
AI_INBREEDING_MARKERS = [
    r"as an ai language model",
    r"i don't have personal opinions",
    r"i cannot fulfill this request",
    r"helpful assistant",
    r"generated by ai",
    r"large language model",
]

AI_INBREEDING_PATTERNS = [re.compile(p, re.IGNORECASE) for p in AI_INBREEDING_MARKERS]

# Markers of secondary / editorial content to reject
SECONDARY_MARKERS = [
    r"\baccording to\b",
    r"\banalysts say\b",
    r"\bexperts believe\b",
    r"\bwikipedia\b",
    r"\bencyclop[ae]dia\b",
    r"\bsource:\s*(reuters|ap|afp|bbc|cnn)\b",
    r"\beditor'?s?\s+note\b",
    r"\b(press release|media advisory)\b",
    r"\bisbn[\s:]+\d",
]

# Markers for translated texts (Project Aletheia rules §2.2)
# Reject if literary text claims to be a translation/version
ORIGINALISM_MARKERS = [
    r"\btranslated (from|by|into)\b",
    r"\brichard\s+burton\b",      # common translator for Arabian Nights etc
    r"\benglish\s+version\b",
    r"\brendered\s+into\s+english\b",
    r"\btrans\.\s+by\b",
    r"\boriginally\s+written\s+in\s+([a-z]+)\b",
]

SECONDARY_PATTERNS = [re.compile(p, re.IGNORECASE) for p in SECONDARY_MARKERS]
ORIGINALISM_PATTERNS = [re.compile(p, re.IGNORECASE) for p in ORIGINALISM_MARKERS]


def compute_hash(text: str) -> str:
    """SHA-256 hash of document text."""
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def validate_date(date_str: str | int | None, max_year: int = 1930) -> bool:
    """Check if a date string/year is at or before the cutoff.

    Returns True if the date is valid (≤ max_year) or unknown.
    """
    if date_str is None:
        return True  # unknown date → handled by source check

    if isinstance(date_str, int):
        return date_str <= max_year

    # Try to parse year from various formats
    for fmt in ("%Y", "%Y-%m-%d", "%d/%m/%Y", "%B %d, %Y"):
        try:
            parsed = datetime.strptime(str(date_str).strip(), fmt)
            return parsed.year <= max_year
        except ValueError:
            continue

    # Try extracting bare year
    match = re.search(r"\b(\d{4})\b", str(date_str))
    if match:
        return int(match.group(1)) <= max_year

    return True  # can't parse → assume OK


def validate_source(source_url: str) -> bool:
    """Check if a source URL is on the approved list."""
    for approved in APPROVED_SOURCES:
        if approved in source_url.lower():
            return True
    return False


def detect_secondary_content(text: str, threshold: int = 3) -> bool:
    """Detect if text contains secondary-source markers.

    Returns True if the text appears to be secondary (REJECT).
    """
    hits = sum(1 for pat in SECONDARY_PATTERNS if pat.search(text))
    return hits >= threshold


def quarantine_check(
    document: dict[str, Any],
    corpus_type: str = "classical",
) -> tuple[bool, str]:
    """Run full quarantine validation on a document.

    Args:
        document: Dict with keys: "text", "date", "source", "lang".
        corpus_type: "classical" (pre-1930) or "modern" (primary sources).

    Returns:
        (passed, reason): Whether the document passed and why/why not.
    """
    text = document.get("text", "")
    date = document.get("date")
    source = document.get("source", "")

    if not text.strip():
        return False, "Empty document"

    if corpus_type == "classical":
        if not validate_date(date, max_year=1930):
            return False, f"Date {date} exceeds 1930 cutoff"
        if detect_secondary_content(text, threshold=2):
            return False, "Secondary-source markers detected in classical text"
        # Strict Originalism Check (§2.2)
        if any(pat.search(text[:2000]) for pat in ORIGINALISM_PATTERNS):
            return False, "Detected translation markers (Project Aletheia rule: Original languages only)"
    elif corpus_type in ["modern", "stem", "cyber", "syntax"]:
        # Temporal hard-stop for modern/tech data to avoid inbreeding
        if not validate_date(date, max_year=2021):
            return False, f"Date {date} exceeds 2021 AI-inbreeding cutoff"
            
        if not validate_source(source):
            return False, f"Source '{source}' not on approved list"
            
        if detect_secondary_content(text, threshold=3):
            return False, "Secondary-source markers detected in text"
            
        # AI Inbreeding Audit (§2.5)
        if any(pat.search(text[:5000]) for pat in AI_INBREEDING_PATTERNS):
            return False, "Detected AI-generated text markers (AI inbreeding filter)"

    return True, "Passed"


def log_audit(
    document: dict[str, Any],
    passed: bool,
    reason: str,
    log_path: str | Path = "data/audit/quarantine_log.jsonl",
) -> None:
    """Append quarantine result to audit log."""
    log_path = Path(log_path)
    log_path.parent.mkdir(parents=True, exist_ok=True)

    entry = {
        "hash": compute_hash(document.get("text", "")),
        "source": document.get("source", ""),
        "date": str(document.get("date", "")),
        "lang": document.get("lang", ""),
        "passed": passed,
        "reason": reason,
        "timestamp": datetime.now().isoformat(),
    }

    with open(log_path, "a", encoding="utf-8") as f:
        f.write(json.dumps(entry) + "\n")
